package com.example.ui.utils

object AppStrings {
    fun get(key: String, lang: String): String {
        return if (lang == "hi") {
            HindiStrings[key] ?: EnglishStrings[key] ?: key
        } else {
            EnglishStrings[key] ?: key
        }
    }
}

val EnglishStrings = mapOf(
    "settings" to "Settings",
    "profile" to "Profile",
    "daily_credits" to "Daily Credits",
    "preferences" to "Preferences",
    "dark_mode" to "Dark Mode",
    "dark_mode_desc" to "Switch to dark theme",
    "voice_responses" to "Voice Responses",
    "voice_responses_desc" to "Read answers aloud",
    "vibration" to "Vibration",
    "vibration_desc" to "Vibrate when answer is received",
    "about_privacy" to "About & Privacy",
    "about_dev" to "About & Developer",
    "about_dev_desc" to "Learn about the app and developer",
    "privacy_policy" to "Privacy Policy",
    "privacy_policy_desc" to "Read our privacy policy and disclaimer",
    "app_language" to "App Language",
    "app_language_desc" to "Select your preferred language",
    "home" to "Home",
    "chat" to "Chat",
    "translator" to "Translator",
    "history" to "History",
    "subjects" to "Subjects",
    "select_subject" to "Select Subject",
    "ai_assistant" to "AI Assistant",
    "ai_translator" to "AI Translator",
    "enter_question" to "Enter Your Question",
    "type_question" to "Type your question here...",
    "tap_upload" to "Tap to upload image",
    "get_ai_answer" to "Get AI Answer (1 Credit)",
    "ai_answer" to "AI Answer",
    "explain" to "Explain",
    "explanation" to "Explanation",
    "translate_text" to "Translate Text",
    "translating" to "Translating...",
    "translate" to "Translate",
    "enter_text_translate" to "Enter text to translate...",
    "result" to "Result",
    "ask_me_anything" to "Ask me anything...",
    "out_of_credits" to "Out of Credits!",
    "out_of_credits_desc" to "You've run out of your 20 free daily credits. Get more credits to continue using AI.",
    "monthly_plan" to "Monthly Plan",
    "credits" to "Credits",
            "refresh_in" to "Refresh in:",
    "available" to "available",
    "hello" to "Hello",
    "here_to_help" to "Here to help you learn",
    "welcome" to "Welcome to Study AI",
    "personalize" to "Let's personalize your experience",
    "your_name" to "Your Name",
    "your_class" to "Your Class/Grade",
    "save_continue" to "Save & Continue",
    "class_grade" to "Your Class/Grade (e.g., Class 10)",
    "pref_app_lang" to "Preferred App Language",
    "english" to "English",
    "hindi" to "Hindi (हिंदी)",
    "from" to "From",
    "to" to "To",
    "tap_to_change" to "Tap to change",
    "student" to "Student",
    "ai_study_assistant" to "AI Study Assistant",
    "type_message" to "Type your message...",
    "math" to "Math",
    "physics" to "Physics",
    "chemistry" to "Chemistry",
    "biology" to "Biology",
    "history_subj" to "History",
    "geography" to "Geography",
    "computer" to "Computer",
    "economics" to "Economics",
    "gk" to "GK",
    "question_history" to "Question History",
    "clear_history" to "Clear History",
    "no_history_yet" to "No history yet"
    , "request_subject" to "Request Subject",
    "request_subject_desc" to "Suggest a new subject to add",
    "request_subject_title" to "Request New Subject",
    "subject_name" to "Subject Name",
    "submit" to "Submit",
    "cancel" to "Cancel",
    "subject_requested" to "Subject requested successfully!"
)

val HindiStrings = mapOf(
    "settings" to "सेटिंग्स",
    "profile" to "प्रोफ़ाइल",
    "daily_credits" to "दैनिक क्रेडिट",
    "preferences" to "प्राथमिकताएं",
    "dark_mode" to "डार्क मोड",
    "dark_mode_desc" to "डार्क थीम पर स्विच करें",
    "voice_responses" to "आवाज़ प्रतिक्रियाएं",
    "voice_responses_desc" to "उत्तर जोर से पढ़ें",
    "vibration" to "कंपन",
    "vibration_desc" to "उत्तर प्राप्त होने पर कंपन करें",
    "about_privacy" to "बारे में और गोपनीयता",
    "about_dev" to "ऐप और डेवलपर के बारे में",
    "about_dev_desc" to "ऐप और डेवलपर के बारे में जानें",
    "privacy_policy" to "गोपनीयता नीति",
    "privacy_policy_desc" to "हमारी गोपनीयता नीति पढ़ें",
    "app_language" to "ऐप की भाषा",
    "app_language_desc" to "अपनी पसंदीदा भाषा चुनें",
    "home" to "होम",
    "chat" to "चैट",
    "translator" to "अनुवादक",
    "history" to "इतिहास",
    "subjects" to "विषय",
    "select_subject" to "विषय चुनें",
    "ai_assistant" to "एआई सहायक",
    "ai_translator" to "एआई अनुवादक",
    "enter_question" to "अपना प्रश्न दर्ज करें",
    "type_question" to "अपना प्रश्न यहाँ टाइप करें...",
    "tap_upload" to "छवि अपलोड करने के लिए टैप करें",
    "get_ai_answer" to "एआई उत्तर प्राप्त करें (1 क्रेडिट)",
    "ai_answer" to "एआई उत्तर",
    "explain" to "समझाइये",
    "explanation" to "स्पष्टीकरण",
    "translate_text" to "अनुवाद करें",
    "translating" to "अनुवाद हो रहा है...",
    "translate" to "अनुवाद",
    "enter_text_translate" to "अनुवाद करने के लिए टेक्स्ट दर्ज करें...",
    "result" to "परिणाम",
    "ask_me_anything" to "मुझसे कुछ भी पूछें...",
    "out_of_credits" to "क्रेडिट समाप्त!",
    "out_of_credits_desc" to "आपके 20 मुफ़्त दैनिक क्रेडिट समाप्त हो गए हैं। एआई का उपयोग जारी रखने के लिए और क्रेडिट प्राप्त करें।",
    "monthly_plan" to "मासिक योजना",
    "credits" to "क्रेडिट",
            "refresh_in" to "में रीफ्रेश होगा:",
    "available" to "उपलब्ध",
    "hello" to "नमस्ते",
    "here_to_help" to "यहाँ मदद के लिए हूँ",
    "welcome" to "स्टडी एआई में आपका स्वागत है",
    "personalize" to "आइए आपके अनुभव को वैयक्तिकृत करें",
    "your_name" to "आपका नाम",
    "your_class" to "आपकी कक्षा/ग्रेड",
    "save_continue" to "सहेजें और जारी रखें",
    "class_grade" to "आपकी कक्षा/ग्रेड (जैसे, कक्षा 10)",
    "pref_app_lang" to "पसंदीदा ऐप भाषा",
    "english" to "English",
    "hindi" to "Hindi (हिंदी)",
    "from" to "से",
    "to" to "में",
    "tap_to_change" to "बदलने के लिए टैप करें",
    "student" to "छात्र",
    "ai_study_assistant" to "एआई स्टडी असिस्टेंट",
    "type_message" to "अपना संदेश टाइप करें...",
    "math" to "गणित",
    "physics" to "भौतिक विज्ञान",
    "chemistry" to "रसायन विज्ञान",
    "biology" to "जीव विज्ञान",
    "history_subj" to "इतिहास",
    "geography" to "भूगोल",
    "computer" to "कंप्यूटर",
    "economics" to "अर्थशास्त्र",
    "gk" to "सामान्य ज्ञान",
    "question_history" to "प्रश्न इतिहास",
    "clear_history" to "इतिहास साफ़ करें",
    "no_history_yet" to "अभी कोई इतिहास नहीं"
    , "request_subject" to "विषय का अनुरोध करें",
    "request_subject_desc" to "जोड़ने के लिए एक नया विषय सुझाएं",
    "request_subject_title" to "नए विषय का अनुरोध करें",
    "subject_name" to "विषय का नाम",
    "submit" to "जमा करें",
    "cancel" to "रद्द करें",
    "subject_requested" to "विषय का अनुरोध सफलतापूर्वक किया गया!"
)
